#!/bin/bash
# ee: A shell script to start and connect to named emacs servers
# Copyright 2010 Victor Chudnovsky
#
# Author: victor.chudnovsky+ee@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Description:
#
# This shell script can be used to start a new named emacs server
# process, or to connect to an already running emacs server process
# with the given name. You can also connect to a singleton unnamed
# emacs server, which is useful if you set the EDITOR shell variable
# to be this script. If the desktop-autosave.el package is installed,
# this script will also start autosaving the desktop, so that you can
# quickly recover context should your session ever die or hang.
#
# Usage: Run this script with the --help flag to see a summary of the
# usage.
#
#    ee -c SERVER FILE.... 
#      connects to SERVER (creating it if necessary) and opens
#      FILE... in a new frame (X or text). The buffer persists even when
#      the frame is closed
#    ee FILE...
#      connects to an unnamed emacs daemon (creating it if necessary)
#      and opens FILE... in a new frame (X or text). The buffer is
#      removed from the server when the frame is closed. This is ideal
#      for using as the value of \$EDITOR
#    ee -l
#      lists all the desktop sessions that have been saved.
#    ee -k SERVER
#      kills the specified running emacs server
#    ee --killall
#      kills all the running emacs servers
#    ee -d SERVER
#      deletes from disk the specified emacs server's desktop file
#    ee --deleteall
#      deletes from disk all the emacs servers' desktop files
#    ee --debug ...
#      displays additional trace information while executing this script
#    ee  --help
#      displays this message
#
#   Advanced  flags (used for bash autocompletion, typically in ee_autocomplete.sh):
#     --user_flags
#       list of flags users would typically use to invoke ee on the
#       command line.
#     --flags_taking_sessions
#       list of flags whose values could be an existing emacs server or
#       desktop name. This list is formatted for use in a bash case
#       statement.
#
# Installation:
# 1. Put the ee script somewhere on your path
# 2. If desired, install the desktop-autosave.el package so that it gets
#    loaded when emacs starts
# 3. Put the ee_autcomplete.sh script somewhere (either at the system
#    level in /etc/bash_completion.d or under your home directory)
# 4. Add the following to your .bashrc so that the ee_autocomplete.sh script gets
#    sourced:
#      . <PATH_TO_EE_AUTOCOMPLETE>/ee_autocomplete.sh
# 5. Add the following to your .bashrc in order to have your deault
#    system editor come up quickly (since this will be a persitent emacs
#    server only instantiated once):
#      export EDITOR=ee
#
# Customization:
#
# The environment variable EMACS_DESKTOP_REPOSITORY controls where the
# saved desktops are placed. If not set, desktops are saved to
# ${HOME}/.emacs.d/desktop-session


# list_sessions
# List all the desktop sessions under $EMACS_DESKTOP_REPOSITORY.
function list_sessions() {
    pushd "$EMACS_DESKTOP_REPOSITORY" >& /dev/null
    if [[ $? ]]; then
	ls */.emacs.desktop 2> /dev/null | sed 's/\([^\/]\)\(\/\.emacs\.desktop\)/\1/'
	popd >& /dev/null
    fi
}

# decho MESSAGE
# Echo a message only in debug mode
function decho() {
    if [[ "$DEBUG" ]]; then
	echo "$*"
    fi
}

# call_emacs DESKTOP_SOCKET DETACH_CMD EMACS_EVAL USE_ALTERNATE_EDITOR
# Invoke emacsclient using DESKTOP_SOCKET and passing DETACH_CMD as a
# flag determining whether to detach from the terminal or not. Also
# cause emacs to evaluate EMACS_EVAL. Tell emacsclient to use an
# alternate editor if USE_ALTERNATE_EDITOR is non-empty; otherwise
# tell emacs to start the server.
function call_emacs() {
    local DESKTOP_SOCKET="$1"
    local DETACH="$2"
    local EVAL="$3"
    if [[ -n "$4" ]]; then
	local ALTERNATE="-a \"\""
    fi
    if  [[ -n "$EVAL" ]]; then
	local DOEVAL="--eval"
	local EVAL="(progn $EVAL )"
    fi
    local CMD="unset ALTERNATE_EDITOR ; emacsclient -c -s \"$DESKTOP_SOCKET\" $DETACH $ALTERNATE $DOEVAL \"\$EVAL\" $REDIRECTION"
    if [[ "$DEBUG" ]]; then
	echo "EVAL:           $EVAL"
	echo "$CMD"
    fi
    eval $CMD
}

# confirm PROMPT
# Print a confirmation prompt and process the user response. A return
# value of 0 corresponds to a user reply of "yes".
function confirm() {
    read -p "$1"
    [[ $REPLY =~ ^[Yy].*$ ]]
    return $?
}

# kill_emacs SESSION
# Kill the running emacs server named SESSION after getting
# confirmation from the user. A return value of 1 means something was
# killed.
function kill_emacs() {
    local DESKTOP_SOCKET_DIR="/tmp/ee/$1"
    local DESKTOP_SOCKET="$DESKTOP_SOCKET_DIR/.socket"
    confirm "Really kill session $1? "
    if (( ! $? )); then
	call_emacs "$DESKTOP_SOCKET" "-n" \
	    "(progn (if (fboundp 'desktop-autosave-stop) (desktop-autosave-stop t)) (kill-emacs))"
	if (( ! $? )); then
	    return 1
	fi
    fi
    return 0
}

# delete_session SESSION
# Delete the desktop session SESSION under ${EMACS_DESKTOP_REPOSITORY}
# after getting confirmation from the user. A return value of 1 means
# something was killed.
function delete_session() {
    local DESKTOP_DIR="${EMACS_DESKTOP_REPOSITORY}/$1"
    confirm "Really delete ${DESKTOP_DIR}? "
    if (( ! $? )); then
	rm -r "${DESKTOP_DIR}"
	if (( ! $? )); then
	    return 1
	fi
    fi
    return 0
}

# destroy_all things DESTROY_FUNCTION DESTROY_LABEL
# Utility function to either kill or delete all ee sessions, since
# both operations follow a similar pattern.  The function actually
# used to perform the destructive operation is DESTROY_FUNCTION. It is
# referred to in user messages as DESTROY_LABEL.
function destroy_all_things() {
    local destroy_function="$1"
    local destroy_label="$2"
    local exit_code=0
    for session in $(list_sessions) ; do
	"$destroy_function" "$session"
	if (( $? )); then
	    echo "Completed $destroy_label on $session"
	else
	    decho "Could not $destroy_label $session"
	    exit_code=1
	fi
    done
    exit $exit_code
}

# destroy_one thing DESTROY_FUNCTION DESTROY_LABEL DESTROY_TARGET
# Utility function to either kill or delete the particular ee session
# DESTROY_TARGET, since both operations follow a similar pattern.  The
# function actually used to perform the destructive operation is
# DESTROY_FUNCTION. It is referred to in user messages as
# DESTROY_LABEL.
function destroy_one_thing() {
    local destroy_function="$1"
    local destroy_label="$2"
    local destroy_target="$3"
    if [[ -z "${destroy_target}" ]]; then
	echo "$0: No session to ${destroy_label} specified"
	exit -1
    fi
    if [[ "$(list_sessions | grep "$destroy_target" )" ]]; then
	"$destroy_function" "$destroy_target"
	exit $?
    else
	echo "$0: The specified desktop session to $destroy_label has not been found. Aborting."
	exit -1
    fi
}

# Recognized flags (FLAG_*) and the values that will be parse from the
# command line (ARG_*).
ARG_HELP="";	     FLAG_HELP="--help"
ARG_LIST="";	     FLAG_LIST="-l"
ARG_CONNECT="";	     FLAG_CONNECT="-c"
ARG_KILL="";	     FLAG_KILL="-k"
ARG_DELETE="";	     FLAG_DELETE="-d"
ARG_KILLALL="";	     FLAG_KILLALL="--killall"
ARG_DELETEALL="";    FLAG_DELETEALL="--deleteall"
ARG_TTY="";	     FLAG_TTY="--tty"
ARG_DEBUG="";	     FLAG_DEBUG="--debug"
ARG_USERFLAGS="";    FLAG_USERFLAGS="--user_flags"
ARG_FLAGSESSIONS=""; FLAG_FLAGSESSIONS="--flags_taking_sessions"
ARG_ENDFLAGS=""      FLAG_ENDFLAGS="--"

# Files to load when connecting to a session.
LOAD_FILE=""

# File to select when starting the client session.
SELECT_FILE=""

# disallow_invalid_flag CURRENT_FLAG PREVIOUS_FLAG 
# Exit with an error if CURRENT_FLAG starts with a dash, so it was
# likely meant as an option. This is intended to catch an intended
# option CURRENT_FLAG directly following a flag PREVIOUS_FLAG that
# takes an argument. However, if ARG_ENDFLAGS is set, this check
# always passes.
function disallow_invalid_flag() {
    if [[ "$1" =~ ^-.* && -z $ARG_ENDFLAGS ]];then
	echo "Invalid flag $1 directly after flag $2. Try $FLAG_HELP."
	exit -2
    fi
}

# append_file FILE PREVIOUS_FLAG
# Appends FILE to SELECT_FILE and LOAD_FILE as appropriate, after
# calling disallow_invalid_flag
function append_file() {
    disallow_invalid_flag "$1" "$2"
    if [[ -z "$SELECT_FILE" ]]; then
	SELECT_FILE="(find-file \"$1\")"
    fi
    LOAD_FILE="$LOAD_FILE (find-file-noselect \"$1\" )"
}

# get_target TARGET PREVIOUS_FLAG
# Sets the global TARGET after calling disallow_invalid_flag
function get_target() {
    disallow_invalid_flag "$1" "$2"
    TARGET="$1"
}

# Parse flags
ARG_LAST=""
while [ $# -gt 0 ]; do
    case "$1" in
	$FLAG_HELP) ARG_HELP=1;;
	$FLAG_LIST) ARG_LIST=1;;
	$FLAG_CONNECT) ARG_CONNECT=1; get_target "$2" "$1"; shift;;
	$FLAG_KILL) ARG_KILL=1; get_target "$2" "$1"; shift;;
	$FLAG_DELETE) ARG_DELETE=1; get_target "$2" "$1"; shift;;
	$FLAG_KILLALL) ARG_KILLALL=1;;
	$FLA_DELETEALL) ARG_DELETEALL=1;;
	$FLAG_TTY) ARG_TTY=1;;
	$FLAG_DEBUG) ARG_DEBUG=1;;
	$FLAG_USERFLAGS) ARG_USERFLAGS=1;;
	$FLAG_FLAGSESSIONS) ARG_FLAGSESSIONS=1;;
	$FLAG_ENDFLAGS) ARG_ENDFLAGS=1;;
	*) append_file "$1" "$ARG_LAST";;	
    esac
    ARG_LAST="$1"
    shift
done

# Don't allow some flag combinations
NUM_EXCLUSIVE_COMMANDS=$(( ARG_LIST + ARG_CONNECT + ARG_KILL + ARG_DELETE + ARG_KILLALL + ARG_DELETE_ALL + ARG_USERFLAGS + ARG_FLAGSESSIONS ))
if [[ "$NUM_EXCLUSIVE_COMMANDS" -gt 1 ]]; then
    echo -e \
	"At most one of of the following flags should be specified:\n" \
	"  $FLAG_LIST $FLAG_CONNECT $FLAG_KILL $FLAG_DELETE $FLAG_KILLALL $FLAG_DELETE_ALL $FLAG_USERFLAGS $FLAG_FLAGSESSIONS"
    exit -1
fi


if [[  -n $ARG_HELP ]]; then
    cat <<EOF
 $0 [OPTIONS] [$FLAG_CONNECT SERVER] [FILE...]
 Run emacs in daemon/client mode, starting the emacs desktop-autosave package
 if available.
   $0 $FLAG_CONNECT SERVER FILE.... 
     connects to SERVER (creating it if necessary) and opens
     FILE... in a new frame (X or text). The buffer persists even when
     the frame is closed
   $0 FILE...
     connects to an unnamed emacs daemon (creating it if necessary)
     and opens FILE... in a new frame (X or text). The buffer is
     removed from the server when the frame is closed. This is ideal
     for using as the value of \$EDITOR
   $0 $FLAG_LIST
     lists all the desktop sessions that have been saved.
   $0 $FLAG_KILL SERVER
     kills the specified running emacs server
   $0 $FLAG_KILLALL
     kills all the running emacs servers
   $0 $FLAG_DELETE SERVER
     deletes from disk the specified emacs server's desktop file
   $0 $FLAG_DELETEALL
     deletes from disk all the emacs servers' desktop files
   $0  $FLAG_HELP
     displays this message
 OPTIONS is one of:
   $FLAG_TTY
     runs in terminal mode, even in an X session
   $FLAG_DEBUG
     displays additional trace information while executing this script

  Advanced  flags (used for bash autocompletion, typically
  in ee_autocomplete.sh):
    $FLAG_USERFLAGS
      list of flags users would typically use to invoke ee on the
      command line.
    $FLAG_FLAGSESSIONS
      list of flags whose values could be an existing emacs server or
      desktop name. This list is formatted for use in a bash case
      statement.

EOF
elif [[ -n $ARG_USERFLAGS ]]; then
    echo "$FLAG_HELP $FLAG_LIST $FLAG_CONNECT $FLAG_KILL $FLAG_DELETE" \
	"$FLAG_KILLALL $FLAG_DELETEALL $FLAG_TTY $FLAG_DEBUG" \
	"$FLAG_USERFLAGS $FLAG_FLAGSESSIONS"
elif [[ -n $ARG_FLAGSESSIONS ]]; then
    echo "${FLAG_CONNECT}|${FLAG_KILL}|${FLAG_DELETE}"
else
    if [[ -z "$DISPLAY" || -n $ARG_TTY ]]; then
	TTY="true"
    else
	TTY=""
    fi

    if [[ -n "$ARG_DEBUG" ]] ; then
	REDIRECTION=""
	shift
    else
	# Only redirect stdout if we're not in a tty--otherwise
	# there's no output device!
	if [[ -n $TTY ]]; then
	    REDIRECTION="2> /dev/null"
	else
	    REDIRECTION=">& /dev/null"
	fi
    fi

    if [[ -z "$EMACS_DESKTOP_REPOSITORY" ]]; then
	EMACS_DESKTOP_REPOSITORY="${HOME}/.emacs.d/desktop-sessions"
    fi
    
    if [[ -n $ARG_LIST ]]; then
	list_sessions
    elif [[ -n $ARG_KILL ]]; then
	destroy_one_thing kill_emacs "kill" "$TARGET"
    elif [[ -n $ARG_KILLALL ]]; then
	destroy_all_things kill_emacs "kill"
    elif [[ -n $ARG_DELETE ]]; then
	destroy_one_thing delete_session "delete" "$TARGET"
    elif [[ -n $ARG_DELETEALL ]]; then
	destroy_all_things delete_session "delete"
    else
	DETACH=""
	EVAL=""
	XDEFAULTS_LOCATION="$HOME/.Xdefaults"

        # We only detach if it's a named server AND we're not in
        # TTY mode
	if [[ -n $TTY ]]; then
	    DETACH="-nw"
	elif [[ -n $ARG_CONNECT ]]; then
	    if [[ -n "$XDEFAULTS_LOCATION" ]]; then
                     # ensure that the X settings for emacs are up to date
		xrdb -merge "$XDEFAULTS_LOCATION"
	    fi
	    DETACH="-n"
	fi
	if [[ -n $ARG_CONNECT ]]; then
	    DESKTOP_NAME="$TARGET"
	    DESKTOP_AUTOSAVE_FORCE="nil"
	else
	    DESKTOP_NAME="ee-desktop"
	    DESKTOP_AUTOSAVE_FORCE="t"
	fi

	DESKTOP_DIR="$EMACS_DESKTOP_REPOSITORY/$DESKTOP_NAME"
	DESKTOP_SOCKET_DIR="/tmp/ee/$DESKTOP_NAME"
	DESKTOP_SOCKET="$DESKTOP_SOCKET_DIR/.socket"

	mkdir -p "$DESKTOP_DIR"
	mkdir -p "$DESKTOP_SOCKET_DIR"

	SERVER_ACCESS="-s \"$DESKTOP_NAME\" -n"

	EVAL="$EVAL (if (fboundp 'desktop-autosave-start) (desktop-autosave-start  \"${DESKTOP_NAME}\" $DESKTOP_AUTOSAVE_FORCE)) $LOAD_FILE $SELECT_FILE"

        # If we just had one file, -c $FILE would work to load and display
        # the one file. In case more than one file is specified, we load
        # and display the first one and just pre-load all the others. We
        # do this by using elisp expressions.  Refer to
        # http://www.gnu.org/s/emacs/manual/html_node/elisp/Visiting-Functions.html#Visiting-Functions


	ALTERNATE=yes

	call_emacs  "$DESKTOP_SOCKET" "$DETACH" "$EVAL" "$ALTERNATE"
    fi
fi # do something